Increase version to 2.2.0p12

diff --git a/templates/check_mk_agent.linux.j2 b/templates/check_mk_agent.linux.j2
--- a/templates/check_mk_agent.linux.j2
+++ b/templates/check_mk_agent.linux.j2
@@ -1620,17 +1620,19 @@ run_cached() {
     fi
 
     # ideally, these should be independent parameters:
-    TIMEOUT=$((MAXAGE * 2))
+    CREATION_TIMEOUT=$((MAXAGE * 2))
+    OUTPUT_TIMEOUT=$((MAXAGE * 3))
 
     [ -d "${MK_VARDIR}/cache" ] || mkdir -p "${MK_VARDIR}/cache"
     CACHEFILE="${MK_VARDIR}/cache/${NAME}.cache"
+    FAIL_REPORT_FILE="${SPOOLDIR}/${NAME}.cachefail"
 
     NOW="$(get_epoch)"
     MTIME="$(get_file_mtime "${CACHEFILE}" 2>/dev/null)" || MTIME=0
 
     if ${MK_RUN_SYNC_PARTS}; then
-        if [ -s "${CACHEFILE}" ]; then
-            # Output the file (even if it is outdated)
+        if [ -s "${CACHEFILE}" ] && [ $((NOW - MTIME)) -le "${OUTPUT_TIMEOUT}" ]; then
+            # Output the file (if it is not too outdated)
             CACHE_INFO="cached(${MTIME},${MAXAGE})"
             # prefix or insert cache info, unless already present.
             # WATCH OUT: AIX does not allow us to pass this as a single '-e' option!
@@ -1641,33 +1643,32 @@ run_cached() {
             fi
         fi
 
-        # Error information about plugin, if available.
-        # Output independent of cachefile existance
-        [ -s "${CACHEFILE}.fail" ] && cat "${CACHEFILE}.fail"
     fi
 
     if ${MK_RUN_ASYNC_PARTS}; then
-        # Kill the process if it is running too long (cache file not accessed for more than TIMEOUT seconds).
+        # Kill the process if it is running too long (cache file not accessed for more than CREATION_TIMEOUT seconds).
         # If killing succeeds, remove CACHFILE.new.PID.
-        # Remove CACHEFILE unconditionally.
-        # Write info about the timed out process and the kill attempt to CACHEFILE.fail.
-        # It will be reported to the Check_MK agent service later on, by the sync part.
-        # CACHEFILE.fail will be deleted as soon as the plugin/local check is functional again.
+        # Write info about the timed out process and the kill attempt to the SPOOLDIR.
+        # It will be reported to the server in the next (synchronous) agent execution.
+        # The file will be deleted as soon as the plugin/local check is functional again.
+        # Do not output the file here, it will interrupt the local and mrpe sections, as well as any other
+        # partially cached section.
         for cfile in "${CACHEFILE}.new."*; do
             [ -e "${cfile}" ] || break # no match
-            if [ $((NOW - $(get_file_atime "${cfile}"))) -ge "${TIMEOUT}" ]; then
+            TRYING_SINCE="$(get_file_atime "${cfile}")"
+            [ -n "${TRYING_SINCE}" ] || break # race condition: file vanished
+            if [ $((NOW - TRYING_SINCE)) -ge "${CREATION_TIMEOUT}" ]; then
                 {
-                    echo "<<<checkmk_cached_plugins:sep(124)>>>"
+                    printf "<<<checkmk_cached_plugins:sep(124)>>>\n"
                     pid="${cfile##*.new.}"
-                    printf "timeout|%s|%s|%s\n" "${NAME}" "${TIMEOUT}" "${pid}"
+                    printf "timeout|%s|%s|%s\n" "${NAME}" "${CREATION_TIMEOUT}" "${pid}"
                     kill -9 "${pid}" >/dev/null 2>&1 && sleep 2 # TODO: what about child processes?
                     if [ -n "$(ps -o args= -p "${pid}")" ]; then
-                        printf "killfailed|%s|%s|%s\n" "${NAME}" "${TIMEOUT}" "${pid}"
+                        printf "killfailed|%s|%s|%s\n" "${NAME}" "${CREATION_TIMEOUT}" "${pid}"
                     else
                         rm -f "${cfile}"
                     fi
-                    rm -f "${CACHEFILE}"
-                } >"${CACHEFILE}".fail 2>&1
+                } >"${FAIL_REPORT_FILE}" 2>&1
             fi
         done
 
@@ -1685,13 +1686,13 @@ run_cached() {
             cat <<HERE | nohup "${CURRENT_SHELL}" >/dev/null 2>&1 &
 eval '${MK_DEFINE_LOG_SECTION_TIME}'
 exec > "${CACHEFILE}.new.\$\$" || exit 1
-$* && mv -f "${CACHEFILE}.new.\$\$" "${CACHEFILE}" && rm -f "${CACHEFILE}.fail" || rm -f "${CACHEFILE}" "${CACHEFILE}.new.\$\$"
+$* && mv -f "${CACHEFILE}.new.\$\$" "${CACHEFILE}" && rm -f "${FAIL_REPORT_FILE}" || rm -f "${CACHEFILE}.new.\$\$"
 HERE
         fi
 
     fi
 
-    unset NAME MAXAGE TIMEOUT REFRESH_INTERVAL CACHEFILE NOW MTIME CACHE_INFO
+    unset NAME MAXAGE CREATION_TIMEOUT REFRESH_INTERVAL CACHEFILE NOW MTIME CACHE_INFO TRYING_SINCE OUTPUT_TIMEOUT
 }
 
 run_local_checks() {
